version: '3.2'

services:

    mysql:
        image: "mysql/mysql-server:8.0.20"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: ais3
            MYSQL_ROOT_PASSWORD: abcde12345
            MYSQL_ROOT_HOST: "%"
            TZ: Asia/Taipei
        restart: unless-stopped

    ais3:
        build: ./
        ports:
            - 3000:3000
        depends_on:
            - mysql
        environment:
            NODE_ENV: dev
        restart: unless-stopped                                      
                                          
